version: '3'
services:

  app: 
    build: . 
    tty: true 
    volumes:
      - .:/go/src/work 
    ports:
      - "8080"
    depends_on: 
      - db

  db:
    image: mysql:latest
    container_name: day27_db
    ports:
      - "3001:3306"
    environment: 
      MYSQL_DATABASE: docker_go
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - ./tmp/mysql:/var/lib/mysql
    command: mysqld

  nginx:
    build: nginx/.
    ports: 
      - 8000:80
    depends_on: 
      - app